app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'ranks#index'

  get 'training/:state' => 'training#index'
  resources :training, only: %i(new create destroy update show) do
    get :is_complete
  end
  resources :sessions, only: %i(new create destroy)
  resources :users, only: %i(new create) do
    get :mypage
    get :training
  end
  resources :goods, only: %i() do
    get :search, on: :collection
    post :search_list, on: :collection
  end
  resources :favorite, only: %i(create destroy)
  resources :training_log, only: %i(create destroy)
  resources :events , only: %i(index)
  
  get '/:genre' => 'ranks#index'
  get '/:genre/:id' => 'ranks#show'


end

app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/app/models/favorite.rb
# == Schema Information
#
# Table name: favorites
#
#  id             :integer          not null, primary key
#  user_id      :integer            not null
#  rank_id      :integer
#  created_at
#  updated_at

class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :rank, optional: true

  validates :user_id, {presence: true}
end

app/app/models/rank.rb
# == Schema Information
#
# Table name: devices
#
#  id             :integer          not null, primary key
#  rank           :integer
#  itemName       :string
#  itemPrice      :integer
#  reviewAverage  :decimal
#  mediumImageUrls:string
#  itemCaption    :text
#  itemUrl      :string 
#  genre      :string 
# 

class Rank < ApplicationRecord
  belongs_to :users, optional: true
  has_many :favorites

  GENRES = {
    ranks: 100984,
    food: 111903,
    drink: 204673,
    sweets: 204655,
    suporters: 204675,
    equipments: 204674,
    others: 101885
  }
end

app/app/models/training.rb
class Training < ApplicationRecord
  belongs_to :users, optional: true
  has_many :training_logs
end

app/app/models/training_log.rb
class TrainingLog < ApplicationRecord
  belongs_to :user
  belongs_to :training, optional: true

  validates :user_id, {presence: true}
end

app/app/models/user.rb
# == Schema Information
#
# Table name: devices
#
#  id                        :integer          not null, primary key
#  name                      :string           not null
#  email                     :integer          not null, uniqueness: true
#  password_digest           :string           not null, length:{minimum: 8} 
#  

class User < ApplicationRecord
  has_secure_password

  # belongs_to :trainings

  has_many :ranks
  has_many :training_logs
  has_many :training_index, through: :training_logs, source: :training
  has_many :favorites
  has_many :favorite_ranks, through: :favorites, source: :rank

  validates :name , {presence: true}
  validates :email, {uniqueness: true, presence: true}
  validates :password, {length: {minimum: 8}}
end

app/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_user

  def index
    @trainings = @user.training_index.where(completed: 1)
  end

  private
  def set_user
    @user = User.find_by(id: @current_user.id);
  end
end

app/app/controllers/favorite_controller.rb
class FavoriteController < ApplicationController

  def create
    @like = Favorite.new(
      user_id: params["user_id"], 
      rank_id: params["rank_id"], 
    )
    @like.save
    flash[:notice] = "お気に入り登録しました"
    redirect_to("/rank/#{params["rank_id"]}")
  end


  def destroy
    @like = Favorite.find_by(
      user_id: params["user_id"], 
      rank_id: params["rank_id"], 
    )
    @like.destroy
    flash[:notice] = "お気に入り登録を解除しました"
    redirect_to("/ranks/#{params["rank_id"]}")
  end
end

app/app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  def search
  end

  def search_list
    if params[:keyword]
      @items = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword], genreId: 100984)
    end  
  end
end

app/app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  before_action :set_item, only: [:show]
  
  def index

    genre = Rank::GENRES
    @rankings = RakutenWebService::Ichiba::Genre[genre[:"#{params[:genre]}"]].ranking.page(params[:page])
    
    ranking_array = []
    @rankings.each do |ranking|
      rank = Rank.new(
        rank: ranking["rank"], 
        itemName:ranking["itemName"], 
        itemPrice:ranking["itemPrice"], 
        itemCaption:ranking["itemCaption"], 
        reviewAverage:ranking["reviewAverage"], 
        mediumImageUrls:ranking["mediumImageUrls"][0], 
        itemUrl: ranking["itemUrl"],
        genre: "#{params[:genre]}"
      );

      rank.save
      ranking_array.push(rank)
    end

    @rankings = Kaminari.paginate_array(ranking_array, total_count: 100).page(params[:page])
    @item = Rank.find_by(genre: params[:genre])
  end

  def show
    @favorite = Favorite.new
  end



  private
  def set_item
    @item = Rank.find_by(id: params[:id])
  end
end

app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:mypage]}
  before_action :forbid_login_user, {only: [:new, :create]}

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "新規登録完了しました"
      redirect_to(user_mypage_path(@user.id))
    else
      flash[:notice] = "新規登録に失敗しました"
      render('new');
    end
  end

  def mypage 
    @user = User.find_by(id: @current_user);
    @favorite_ranks = @user.favorite_ranks
  end

  def training
    @trainings = Training.all
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/events_helper.rb
module EventsHelper
end

app/app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/app/helpers/goods_helper.rb
module GoodsHelper
end

app/app/helpers/ranks_helper.rb
module RanksHelper
end

app/app/helpers/sessions_helper.rb
module SessionsHelper
end

app/app/helpers/training_helper.rb
module TrainingHelper
end

app/app/helpers/training_log_helper.rb
module TrainingLogHelper
end

app/app/helpers/users_helper.rb
module UsersHelper
end

app/app/views/layouts/_category.html.slim
section.l-header__main
  h1.l-header__main__heading.slide
    | 体型が変われば、人生が変わる
  a.l-header__main__btn
    | Genre
section.category
  section.category__contents
    = link_to '/food' do
      .category__contents__content
        img.category__contents__content__image[src="/category_images/food.jpg"]
        h3.category__contents__content__heading
          | Food
    = link_to '/drink' do
      .category__contents__content
        img.category__contents__content__image[src="/category_images/drink.jpg"]
        h3.category__contents__content__heading
          | Drink
    = link_to '/sweets' do
      .category__contents__content
        img.category__contents__content__image[src="/category_images/sweets.jpg"]
        h3.category__contents__content__heading
          | Sweets
    = link_to '/suporters' do
      .category__contents__content
        img.category__contents__content__image[src="/category_images/suporter.jpg"]
        h3.category__contents__content__heading
          | Suporter
    = link_to '/equipments' do
      .category__contents__content
        img.category__contents__content__image[src="/category_images/equipment.jpg"]
        h3.category__contents__content__heading
          | Equipment
    = link_to '/others' do
      .category__contents__content
        img.category__contents__content__image[src="/category_images/others.jpg"]
        h3.category__contents__content__heading
          | Others

app/app/views/layouts/_flash.html.slim
- if flash[:notice]
  .flash
    = flash[:notice]

app/app/views/layouts/_footer.html.slim
footer.l-footer
  p.l-footer__text
    small
      | ©️ 2020 ZeroCalo.

app/app/views/layouts/_header_top.html.slim
header.l-header
  section.l-header__top
    .l-header__top__left
      = link_to("/ranks", data: {"turbolinks" => false}) do
        h2.l-header__top__left__heading
          i.fas.fa-apple-alt
          | ZeroCalo
    .l-header__top__right
      .l-header__top__right__bars
        i.fas.fa-bars.menu
      .l-header__top__right__texts
        nav.l-header__top__right__texts__nav
          p.l-header__top__right__texts__nav__heading
            i.fas.fa-crown
            | Ranking
          ul.l-header__top__right__texts__nav__lists
            = link_to( "/ranks") do
              li.l-header__top__right__texts__nav__lists__list
                | ALL
            = link_to( "/food") do
              li.l-header__top__right__texts__nav__lists__list
                | FOOD
            = link_to( "/drink") do
              li.l-header__top__right__texts__nav__lists__list
                | DRINK
            = link_to( "/sweets") do
              li.l-header__top__right__texts__nav__lists__list
                | SWEETS
            = link_to( "/suporters") do
              li.l-header__top__right__texts__nav__lists__list
                | SUPORT
            = link_to( "/equipments") do
              li.l-header__top__right__texts__nav__lists__list
                | EQUIPMENT
            = link_to( "/others") do
              li.l-header__top__right__texts__nav__lists__list
                | OTHERS
        = link_to search_goods_path do
          .l-header__top__right__texts__lists
            p.l-header__top__right__texts__lists__heading
              | Goods Search
        - if session[:user_id]
          = link_to "/training/all" ,{method: "get"} do
            .l-header__top__right__texts__lists
              p.l-header__top__right__texts__lists__heading
                | Training
        - if session[:user_id]
          = link_to session_path(@current_user.id) ,{method: "delete"} do
            .l-header__top__right__texts__lists
              p.l-header__top__right__texts__lists__heading
                | Logout
          = link_to user_mypage_path(@current_user.id) do
            .l-header__top__right__texts__lists
              p.l-header__top__right__texts__lists__heading
                | Mypage
        - else
          = link_to new_user_path do
            .l-header__top__right__texts__lists
              p.l-header__top__right__texts__lists__heading
                | Sign up
          = link_to new_session_path do
            .l-header__top__right__texts__lists
              p.l-header__top__right__texts__lists__heading
                | Login

app/app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | App
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag '/favicon.ico'
    script[src="https://kit.fontawesome.com/76b7c2052c.js" crossorigin="anonymous"]
    meta[name="viewport" content="width=device-width,initial-scale=1.0"]
  body
    .container
      = render 'layouts/header_top'
      .contents
        = render 'layouts/flash'
        = yield
      = render 'layouts/footer'
      div