app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'ranks#index'

  get 'training/:state' => 'training#index'
  resources :training, only: %i(new create destroy update show) do
    get :is_complete
  end
  resources :sessions, only: %i(new create destroy)
  resources :users, only: %i(new create) do
    get :mypage
    get :training
  end
  resources :goods, only: %i() do
    get :search, on: :collection
    post :search_list, on: :collection
  end
  resources :favorite, only: %i(create destroy)
  resources :training_log, only: %i(create destroy)
  resources :events , only: %i(index)
  
  get '/:genre' => 'ranks#index'
  get '/:genre/:id' => 'ranks#show'


end

app/app/models/training.rb
class Training < ApplicationRecord
  belongs_to :users, optional: true
  has_many :training_logs
end

app/app/controllers/training_controller.rb
class TrainingController < ApplicationController
  before_action :set_training
  before_action :set_training_id
  before_action :set_user

  def index
    if params[:state] == "all"
      @trainings = @user.training_index.order(limit: :asc).page(params[:page])
    elsif params[:state] == "complete"
      @trainings = @user.training_index.where("completed = 1").order(limit: :asc).page(params[:page])
    elsif params[:state] == "in_complete"
      @trainings = @user.training_index.where("completed = 0").order(limit: :asc).page(params[:page])
    end
    training_array = []
    training_array.push(@trainings)
    @training_pagenate = Kaminari.paginate_array(training_array, total_count: 100).page(params[:page])
  end

  def show
  end

  def new
  end

  def update
    if @training.update(training_params)
      flash[:notice] = "トレーニングスケジュールを更新しました。"
      redirect_to(training_index_path)
    else
      flash[:notice] = "トレーニングスケジュールを更新出来ませんでした。"
      render("show")
    end
  end

  def is_complete
    if @training_id.completed == 0
      @training_id.completed = 1
      if @training_id.update(training_params)
        flash[:notice] = "トレーニングお疲れさまです。完了しました。"
      end
    elsif @training_id.completed == 1
      @training_id.completed = 0
      if @training_id.update(training_params)
        flash[:notice] = "トレーニングが完了していません。"
      end
    end
    redirect_to(training_index_path)
  end


  def training_events
    @trainings = @user.training_index
    respond_to do |format|
      format.any { render json: @trainings.to_json( only: [:tasks, :limit] ) }
    end
  end





  private
  def set_training
    @training = Training.find_by(id: params[:id])
  end

  def set_training_id
    @training_id = Training.find_by(id: params[:training_id])
  end

  def set_user
    @user = User.find_by(id: @current_user.id);
  end

  def training_params
    params.permit(:tasks, :content, :limit, :completed, :user_id)
  end
end

app/app/helpers/training_helper.rb
module TrainingHelper
end

app/app/views/training/_training-contents_header.html.slim
.training-contents_header
  .training-contents_header_left
    .training-contents_heading
      h2.training-contents_heading_content.heading
        | Tarining List
    .training-contents_text
      p.training-contents_text_content
        | 日々のトレーニングのスケジュールを管理しましょう。
  .training-contents_header_right
    a.calender href="#{events_path}"
      i.far.fa-calendar-alt
  
.training-contents_btn
    = link_to(new_training_path) do
      .new-btn
        | CREATE NEW TRAINING

app/app/views/training/_training_list.html.slim
.training-contents_index
  table.table 
    tr
      th State
      th Training
      th.contents_none contents
      th Day
    - for training in trainings
      tr
        - if training.completed == 0
          td.state.incomplete 
            | Incomplete
        - elsif training.completed == 1
          td.state.complete 
            | Complete
        td = link_to  training_path(training.id), class: "tasks"
            = training.tasks
        td.contents_none = truncate(training.content, length:15)
        td = training.limit
        td
          = link_to  training_is_complete_path(training.id), class: 'complete-btn'
            i.fas.fa-check-circle.complete-btn
      
= paginate @training_pagenate, total_pages: 10

.search
  .search_all
    = link_to "/training/all", class: "search_state search_all"
      | All
  .search_complete
    = link_to "/training/complete", class: "search_state search_complete"
      | Complete
  .search_incomplete
    = link_to "/training/in_complete", class: "search_state search_incomplete"
      | Incomplete

app/app/views/training/index.html.slim
section.training-contents.index
  = render partial: 'training/training-contents_header'
  = render partial: 'training/training_list', locals: { trainings: @trainings }
  
  

app/app/views/training/new.html.slim
section.new-tasks.index
  .new-tasks_heading
    h2.new-tasks_heading_content.heading
      | NEW TRAINING

  = form_with  url: training_log_index_path ,class: "form_class", method: :post, local: true do |f|
    = f.label :tasks, 'トレーニング名'
    = f.text_field :tasks, id: "tasks"
    = f.label :content, 'トレーニング内容'
    = f.text_area :content, id: "content"
    = f.label :limit, '日付'
    = f.date_field :limit, id: "limit"
    = f.hidden_field :completed, :value => 0, id: 'task_completed'
    = f.hidden_field :user_id, :value => @current_user.id
    = f.submit "新規登録", class: "submit"

app/app/views/training/show.html.slim
section.new-tasks.index
  .new-tasks_heading
    h2.new-tasks_heading_content.heading
      | EDIT TRAINING
  .form-contents
    = form_with  model: @trainig, method: :put, class: "form_class", local: true do |f|
      = f.label :tasks, 'トレーニング名'
      = f.text_field :tasks, value: @training.tasks, id: "tasks"
      = f.label :content, 'トレーニング内容'
      = f.text_area :content, value: @training.content , id: "content"
      = f.label :limit, '日付'
      = f.date_field :limit, value: @training.limit , id: "limit"
      = f.hidden_field :completed, :value => 0, id: 'task_completed'
      = f.hidden_field :user_id, :value => @current_user.id
      = f.submit "更新", class: "submit show-btn"
  .show-btns
    a.show-btn.show_delete href="/training_log/#{@training.id}"
      |削除