app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'ranks#index'

  get 'training/:state' => 'training#index'
  resources :training, only: %i(new create destroy update show) do
    get :is_complete
  end
  resources :sessions, only: %i(new create destroy)
  resources :users, only: %i(new create) do
    get :mypage
    get :training
  end
  resources :goods, only: %i() do
    get :search, on: :collection
    post :search_list, on: :collection
  end
  resources :favorite, only: %i(create destroy)
  resources :training_log, only: %i(create destroy)
  resources :events , only: %i(index)
  
  get '/:genre' => 'ranks#index'
  get '/:genre/:id' => 'ranks#show'


end

app/app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  def search
  end

  def search_list
    if params[:keyword]
      @items = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword], genreId: 100984)
    end  
  end
end

app/app/helpers/goods_helper.rb
module GoodsHelper
end

app/app/views/goods/search.html.slim
section.goods-search
  .goods-search__texts
    p.goods-search__texts__text
      | 商品名
  .goods-search__input
    = form_with url: search_list_goods_path, name: "keyword", class: "input", local: true do |f|
      = f.text_field :keyword
      button.search-btn[type="submit" name="commit" value="" data-disable-with=""]
        | 検索

app/app/views/goods/search_list.html.slim
= render 'layouts/category'
.search-result
  p.search-result__text
    | 検索結果: 
    span.search-result__genre
      = params[:keyword]
section.index
  - @items.each do |item|
    = link_to( item.url, :target=>["_blank"]) do
      .index__contents
        .index__contents__content
          .index__contents__content__images
            = image_tag item.medium_image_urls[0], class: 'index__contents__content__images__image'
          .index__contents__content__texts
            h2.index__contents__content__texts__text
              = truncate(item.name, length:60)
            .price_review
              p.index__contents__content__texts__price
                span.fee
                  = item.price
                | 円(税込)
              p.index__contents__content__texts__review
                = item.review_average
                span.reviewMax
                  | /5